### ISSUE TITLE
Minio pool error trying to mount volumes using Directpv

### ISSUE THREAD

**Issue by elissonrusiel** [minio/directpv#588]
After installing the minio-operator and I am getting errors in the assembly of the volumes with directpv.
The PVCs and PVs have been correctly provisioned, but I have caught bind mount errors in the direct-csi container.
 

```
I0519 07:28:01.517718 1607570 mount_linux.go:126] "bind mounting directory" source="/var/lib/direct-csi/mnt/5f66fed7-fd5a-b33a-e059-d175b14c179b/pvc-aeebf859-6c02-4d37-9602-e93a1e9c3bc2" target="/var/snap/microk8s/common/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-aeebf859-6c02-4d37-9602-e93a1e9c3bc2/globalmount" fsType="xfs" recursive=false readOnly=false superBlockFlags="prjquota"
E0519 07:28:01.517747 1607570 server.go:92] GRPC error: rpc error: code = Internal desc = failed stage volume: no such file or directory
```
On my host I have the volumes properly created 
```
/var/lib/direct-csi/mnt/
├── 5f66fed7-fd5a-b33a-e059-d175b14c179b
│   ├── pvc-20ed3004-400a-4612-b16b-c66216ec021f
│   ├── pvc-23644b85-67c8-4b0c-880b-78737f4c293b
│   ├── pvc-5ea4c94d-2dd5-47f4-9be2-a6e558cfbf33
│   └── pvc-aeebf859-6c02-4d37-9602-e93a1e9c3bc2
└── ce4d4157-bb23-3fbb-5b7e-948503edfe34

6 directories, 0 files
```

**Comment by elissonrusiel** [comment]
Hi I was able to solve the problem by mounting a Microk8s root volume in the daemonset. I'm not sure if this is the best solution though.

```
volumeMounts:
- mountPath: /var/snap/microk8s
  mountPropagation: Bidirectional
  name: microk8s
```

```
volumes:
- hostPath:
  path: /var/snap/microk8s
  type: DirectoryOrCreate
  name: microk8s
```
