### ISSUE TITLE
Tolerations usage with the directpv cli

### ISSUE THREAD

**Issue by leon-andria** [minio/directpv#706]
I would to schedule the DaemonSet to all my nodes even node with taints.

From yaml, I believe the following syntax should work:
```
tolerations:
  - operator: "Exists"
```

The question is how we can do this in the cli ? I tried many syntax, but looks like the parser here https://github.com/minio/directpv/blob/774f63ff8c6bcf7bf304c05abc639aafd8a70915/cmd/kubectl-directpv/validators.go#L138 is quiet strict.

`kubectl directpv install --dry-run -o yaml --tolerations "Exists:NoSchedule"`

The syntax above produces Exists as key which is surprisingly.

```
tolerations:
      - effect: NoSchedule
        key: Exists
        operator: Exists
```

**Comment by balamurugana** [comment]
There are plenty of bugs fixed in [devel branch](https://github.com/minio/directpv/tree/devel) and you could try a snapshot build for testing
1.  Download DirectPV `kubectl` plugin from GNU/Linux at https://github.com/balamurugana/directpv/releases/download/v3.1.0-40-gd2dec861-6-gfbabf7d7/kubectl-directpv
2. Set execute permission like `$ chmod a+x kubectl-directpv`
3. Install DirectPV snapshot by `$ ./kubectl-directpv install --registry docker.io --org baladevel`

**Comment by leon-andria** [comment]
I'm not sure how this is answering my initial question.

What is the equivalent syntax to be used with the cli for yaml below ?

```
tolerations:
  - operator: "Exists"
```

**Comment by balamurugana** [comment]
Have you tried `--torelations KEY:EFFECT`?

**Comment by leon-andria** [comment]
Yes and this leads to this:
```
tolerations:
      - effect: NoSchedule
        key: Exists
        operator: Exists
```
which is wrong.
