### ISSUE TITLE
The created SC cannot be used

### ISSUE THREAD

**Issue by jieshiyeskey** [minio/directpv#735]
**Basic information**
`
kubernetes-v1.26.3
`
`
directpv version v4.0.1
`

```
#kubectl get sc
NAME              PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
directpv-min-io   directpv-min-io   Delete          WaitForFirstConsumer   true                   13h
```

**Test example**
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-m
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis-m
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4-alpine
        ports:
        - containerPort: 6379
          name: redisport
        volumeMounts:
        - mountPath: /data
          name: redisdata
  volumeClaimTemplates:
    - metadata:
        name: redisdata
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
        storageClassName: directpv-min-io
```

** Result**
```
# kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                         STORAGECLASS      REASON   AGE
pvc-f45a06ec-de2b-4429-8c4f-3b5617d0f507   1Gi        RWO            Delete           Bound    default/redisdata-redis-m-0   directpv-min-io            12m		


# kubectl get pvc
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
redisdata-redis-m-0   Bound    pvc-f45a06ec-de2b-4429-8c4f-3b5617d0f507   1Gi        RWO            directpv-min-io   12m	

# kubectl get pod
NAME                        READY   STATUS              RESTARTS      AGE
redis-m-0                   0/1     ContainerCreating   0             13m
```
**Logs**
```
# kubectl describe  pod redis-m-0
Name:             redis-m-0
Namespace:        default
Priority:         0
Service Account:  default
Node:             cn-cp-1/172.16.0.11
Start Time:       Sun, 26 Mar 2023 22:18:47 +0800
Labels:           app=redis
                  controller-revision-hash=redis-m-57cc8c6b88
                  statefulset.kubernetes.io/pod-name=redis-m-0
Annotations:      <none>
Status:           Pending
IP:
IPs:              <none>
Controlled By:    StatefulSet/redis-m
Containers:
  redis:
    Container ID:
    Image:          redis:4-alpine
    Image ID:
    Port:           6379/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from redisdata (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-4tfxt (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  redisdata:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  redisdata-redis-m-0
    ReadOnly:   false
  kube-api-access-4tfxt:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    13m                  default-scheduler  Successfully assigned default/redis-m-0 to cn-cp-1
  Warning  FailedMount  5m1s (x4 over 11m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[redisdata], unattached volumes=[redisdata kube-api-access-4tfxt]: timed out waiting for the condition
  Warning  FailedMount  89s (x14 over 13m)   kubelet            MountVolume.SetUp failed for volume "pvc-f45a06ec-de2b-4429-8c4f-3b5617d0f507" : rpc error: code = Internal desc = stagingPath /var/lib/kubelet/plugins/kubernetes.io/csi/directpv-min-io/12cef50beac8e7fc71143fc1409b40ca77b2159e1c0ef1c7151d8f9dbda59b1c/globalmount is not mounted
  Warning  FailedMount  32s (x2 over 2m46s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[redisdata], unattached volumes=[kube-api-access-4tfxt redisdata]: timed out waiting for the condition
```

**Problem**
The preceding information is displayed to keep the pod in the ContainerCreating state. Previous directpv version has also been saved this problem, please master to check, thanks.
