### ISSUE TITLE
Trying to get PVC work.

### ISSUE THREAD

**Issue by bobacarOrpheo** [minio/directpv#766]
Operator v5.0.4
Directpv v4.0.4
Kubernetes as SaaS at OVH, v1.26.4 no flavor.

I'm trying to test Minio, so i took a pool of 4 nodes (4 CPU, 8Go RAM, 50Go HDD) where i added a disk of 10 Go for each node.

So first i made and applied the directpv storage class and tried those commands:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: directpv-min-io
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```
```bash
kubectl krew install directpv
kubectl directpv install
kubectl directpv info
kubectl directpv discover
kubectl directpv init drives.yaml
kubectl directpv list drives
┌────────────────────────────────────────────┬──────┬────────────────────┬────────┬────────┬─────────┬────────┐
│ NODE                                       │ NAME │ MAKE               │ SIZE   │ FREE   │ VOLUMES │ STATUS │
├────────────────────────────────────────────┼──────┼────────────────────┼────────┼────────┼─────────┼────────┤
│ nodepool-7def296b-ad88-4211-a6-node-09c8d3 │ sdb  │ QEMU QEMU_HARDDISK │ 10 GiB │ 10 GiB │ -       │ Ready  │
│ nodepool-7def296b-ad88-4211-a6-node-4056ca │ sdb  │ QEMU QEMU_HARDDISK │ 10 GiB │ 10 GiB │ -       │ Ready  │
│ nodepool-7def296b-ad88-4211-a6-node-a91a5b │ sdb  │ QEMU QEMU_HARDDISK │ 10 GiB │ 10 GiB │ -       │ Ready  │
│ nodepool-7def296b-ad88-4211-a6-node-ed9ab7 │ sdb  │ QEMU QEMU_HARDDISK │ 10 GiB │ 10 GiB │ -       │ Ready  │
└────────────────────────────────────────────┴──────┴────────────────────┴────────┴────────┴─────────┴────────┘
```
After that i created the PVC that i applied with kubectl:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
spec:
  storageClassName: directpv-min-io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
Then i went to the Operator Console to create a tenant, where i indicated 4 servers with one drive, and total capacity of 40Gi (tried less too in case of, same).

Problem is that i am stuck to this state: Provisioning initial users
With this error in the Pods section:

Warning	FailedScheduling
0/4 nodes are available: 4 node(s) didn't find available persistent volumes to bind. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.

PVC is always pending, so i suppose it's not used.
Here is the output for the PVC.
```yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"my-claim","namespace":"default"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":"directpv-min-io"}}
    creationTimestamp: "2023-05-15T08:46:52Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: my-claim
    namespace: default
    resourceVersion: "1721518699"
    uid: b0bcbff0-0bfa-44f9-aadb-c61ec5991abc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: directpv-min-io
    volumeMode: Filesystem
  status:
    phase: Pending
kind: List
metadata:
  resourceVersion: ""
```
Since i was stuck on how to make Minio take the space available from the directpv drives, i used another approach.
I don't like it since it imply manual manipulations.
So i wanted to be sure that the additional 10Go drives where seen by the nodes, so i used this command for debug:
```bash
kubectl debug node/nodepool-7def296b-ad88-4211-a6-node-4056ca -it --image=debian
mount | grep xfs
```
With that, i know that the directpv drive of this node was mounted at this path:
/var/lib/directpv/mnt/87f2bd94-ac01-49f2-84c6-66190cb5438c
I made a PV for each node according to the path i found, for this node it was this PV i applied with kubectl:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
   name: 4056ca
spec:
   capacity:
      storage: 10Gi
   volumeMode: Filesystem
   accessModes:
   - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   storageClassName: directpv-min-io
   local:
      path: /var/lib/directpv/mnt/87f2bd94-ac01-49f2-84c6-66190cb5438c
   nodeAffinity:
      required:
         nodeSelectorTerms:
         - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - nodepool-7def296b-ad88-4211-a6-node-4056ca
```
Like that i was able to create a working tenant, even if the total capacity wasn't took into account at all.
Even if i put 8Gi of total capacity, it took the whole capacity of the capacity of the directpv drives.
When i use the following commands, i see than nothing is used or displayed accordingly even if the tenant is full:
```bash
kubectl directpv list drives
┌────────────────────────────────────────────┬──────┬────────────────────┬────────┬────────┬─────────┬────────┐
│ NODE                                       │ NAME │ MAKE               │ SIZE   │ FREE   │ VOLUMES │ STATUS │
├────────────────────────────────────────────┼──────┼────────────────────┼────────┼────────┼─────────┼────────┤
│ nodepool-7def296b-ad88-4211-a6-node-09c8d3 │ sdb  │ QEMU QEMU_HARDDISK │ 10 GiB │ 10 GiB │ -       │ Ready  │
│ nodepool-7def296b-ad88-4211-a6-node-4056ca │ sdb  │ QEMU QEMU_HARDDISK │ 10 GiB │ 10 GiB │ -       │ Ready  │
│ nodepool-7def296b-ad88-4211-a6-node-a91a5b │ sdb  │ QEMU QEMU_HARDDISK │ 10 GiB │ 10 GiB │ -       │ Ready  │
│ nodepool-7def296b-ad88-4211-a6-node-ed9ab7 │ sdb  │ QEMU QEMU_HARDDISK │ 10 GiB │ 10 GiB │ -       │ Ready  │
└────────────────────────────────────────────┴──────┴────────────────────┴────────┴────────┴─────────┴────────┘
kubectl directpv info
┌──────────────────────────────────────────────┬──────────┬───────────┬─────────┬────────┐
│ NODE                                         │ CAPACITY │ ALLOCATED │ VOLUMES │ DRIVES │
├──────────────────────────────────────────────┼──────────┼───────────┼─────────┼────────┤
│ • nodepool-7def296b-ad88-4211-a6-node-09c8d3 │ 10 GiB   │ 0 B       │ 0       │ 1      │
│ • nodepool-7def296b-ad88-4211-a6-node-4056ca │ 10 GiB   │ 0 B       │ 0       │ 1      │
│ • nodepool-7def296b-ad88-4211-a6-node-ed9ab7 │ 10 GiB   │ 0 B       │ 0       │ 1      │
│ • nodepool-7def296b-ad88-4211-a6-node-a91a5b │ 10 GiB   │ 0 B       │ 0       │ 1      │
└──────────────────────────────────────────────┴──────────┴───────────┴─────────┴────────┘

0 B/40 GiB used, 0 volumes, 4 drives
```
Help to use directpv in the correct way is very welcome, i'm sure i'm missing lots of points to make it work as it was planned.
My end goal is to avoid manipulation of the PV path's, i thought that directpv was doing the job in his side dynamically but i am missunderstand it.

I tried by the way to increase the capacity of a drive mounted to a node, moving from 10Go to 11Go, and adjusting the path in the PV, i was pleasantly surprised to see that my files were still inside and the capacity increase was took into account.

Is it dangerous to make that?
Any risk to have my files corrupted if i make bigger evolutions to try to keep the same pool but make it evolve in terms of capacity?

Thank you in advance for taking the time to read this and trying to help me.

**Comment by balamurugana** [comment]
You would need to follow https://github.com/minio/operator/blob/master/docs/using-direct-pv.md

**Comment by bobacarOrpheo** [comment]
Thank you for the reply @balamurugana .

Any hope to have an insights on how i have to integrate this idea of volumeClaimTemplate?

The PVC i made with 10Gi requested isn't put correctly then.

I tried to check what show the tenant specification inside the Operator console, here what i have for this part:
```yaml
volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "10737418240"
        storageClassName: directpv-min-io
      status: {}
    volumesPerServer: 1
```
