### ISSUE TITLE
`FailedMount`: MountVolume.MountDevice failed for volume "pvc-xxx" even though the volume was mounted

### ISSUE THREAD

**Issue by usersina** [minio/directpv#802]
## Bug description

Setting up `directpv` with newly formatted drives and trying out the `functests/minio.yaml` successfully creates PVs and PVCs that work as intended.

However, creating a tenant will always result in a `ContainerCreating` pod, with the following error message
> kubelet  MountVolume.MountDevice failed for volume "pvc-32c716c8-a767-4434-83d5-823db386df94" : rpc error: code = Internal desc = unable to bind mount volume directory to staging target path; no such file or directory

- `kubectl describe pod staging-tenant-single-pool-0 -n staging`
```
Type     Reason       Age                   From     Message
----     ------       ----                 ----               -------
Normal   Scheduled    4m6s                 default-scheduler  Successfully assigned staging/staging-tenant-single-pool-0 to kube-controller
Warning  FailedMount  2m10s                kubelet  Unable to attach or mount volumes: unmounted volumes=[data0], unattached volumes=[configuration kube-api-access-qxb8x data0 staging-tenant-tls]: timed out waiting for the condition
Warning  FailedMount  2m3s                 kubelet  MountVolume.MountDevice failed for volume "pvc-32c716c8-a767-4434-83d5-823db386df94" : rpc error: code = Internal desc = unable to bind mount volume directory to staging target path; no such file or directory
```

The weird thing is that, `PVs` and `PVCs` for the tenant were indeed created and `Bound`

- `kubectl get pv`
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                        STORAGECLASS        REASON   AGE
pvc-32c716c8-a767-4434-83d5-823db386df94   50Gi       RWO            Delete           Bound    staging/data0-staging-tenant-single-pool-0   directpv-min-io              13m
```

- `kubectl get pvc -n staging`
```
NAME                                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
data0-staging-tenant-single-pool-0   Bound    pvc-32c716c8-a767-4434-83d5-823db386df94   50Gi       RWO            directpv-min-io   13m
```

## To Reproduce

1. [Install directpv](https://github.com/minio/directpv/blob/master/docs/cli.md) and try out the `PV`/`PVC` creation
```
kubectl apply -f functests/minio.yaml
```

2. Install MinIO operator using the Helm Chart
```
helm repo add minio https://operator.min.io/
helm repo update

helm upgrade \
    --install \
    --namespace minio-operator \
    --create-namespace \
    --version "4.5.8" \
    minio-operator minio/operator
```

3. Install MinIO tenant using the Helm Chart

```
helm upgrade -f config.yaml \
    --install \
    --namespace staging \
    --set secrets.accessKey='minioadmin' \
    --set secrets.secretKey='minioadmin' \
    --set tenant.name='staging-tenant' \
    --set tenant.pools[0].size='50Gi' \
    --version "4.5.8" \
    minio-tenant minio/tenant
```

<details>
  <summary>config.yaml</summary>

```yaml
secrets:
  name: minio-tenant-env-conf
  # MinIO root user and password
  accessKey: minioadmin
  secretKey: minioadmin

## MinIO Tenant Definition
tenant:
  name: minio-tenant
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2021-07-30T00-02-00Z
    pullPolicy: IfNotPresent
  configuration:
    name: minio-tenant-env-conf
  pools:
    - servers: 1
      name: single-pool
      volumesPerServer: 1
      size: 50Gi
      storageClassName: directpv-min-io
      resources:
        requests:
          cpu: 1000m
          memory: 2Gi
        limits:
          cpu: 2000m
          memory: 3Gi

  prometheus:
    disabled: true
  log:
    disabled: true
```

</details>

**Note:**
- I specifically use version `4.5.8` since I have the following error trying out the newest version, but that's another issue
```
Users creation failed: Put "https://minio.staging.svc.cluster.local/minio/admin/v3/add-user?accessKey=xxxxxx": dial tcp 10.152.183.83:443: connect: connection refused
```

## Expected behavior
The Pod goes from `ContainerCreating` state to `Ready` state and MinIO tenant is accessible.

## Deployment information
 - DirectPV version: `directpv version v4.0.5`
 - Kubernetes Version:
```
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.26.5
```
 - OS info: `Linux kube-controller 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

## Additional context

I am using `MicroK8s v1.26.5 revision 5395`.

In the past, I had to manually update the `kubelet` path but I assume that is not necessary anymore since the `functests/minio.yaml` now work without this hack.

```bash
# Install kubectl directpv plugin
kubectl krew install directpv

# Generate the .yaml file
kubectl directpv install -o yaml > directpv-install.yaml

# Update the .yaml file by replacing the kubelet path (specific to MicroK8s)
sed -i 's#/var/lib/kubelet/#/var/snap/microk8s/common/var/lib/kubelet/#g' directpv-install.yaml

# Install directpv
kubectl apply -f directpv-install.yaml
```

## Related
- https://github.com/minio/operator/issues/338 (no solution)
- https://github.com/minio/operator/issues/1119 (most likely not the case since the `functests` work)
- https://github.com/minio/operator/issues/1513
