### ISSUE TITLE
node-server Daemonset: unable to execute command" err="DirectPVNode.directpv.min.io

### ISSUE THREAD

**Issue by naguam** [minio/directpv#959]
**Describe the bug**
node-server Daemonset in CrashloopBackOff on a clean install on a kind cluster.

**To Reproduce**
Clean install on a kind cluster with kubernetes 1.31.

```sh
#!/usr/bin/bash

mkdir /scratch/kind-control-plane
mkdir /scratch/kind-worker
mkdir /scratch/kind-worker2

kind create cluster --config multinode.yml
```

```yaml
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /scratch/kind-control-plane
    containerPath: /var/local-path-provisioner
- role: worker
  extraMounts:
  - hostPath: /scratch/kind-worker
    containerPath: /var/local-path-provisioner
- role: worker
  extraMounts:
  - hostPath: /scratch/kind-worker2
    containerPath: /var/local-path-provisioner
...
```

`kubectl directpv install`

**Expected behavior**
node-server should not be in CrashloopBackOff nor Error.

**Screenshots and logs**

```
  node-controller:
    Container ID:  containerd://dc6b480f2a16ab920c28393f546d4d2bb53600e0016c11ead29ad4d3677eb64a
    Image:         quay.io/minio/directpv:v4.1.4
    Image ID:      quay.io/minio/directpv@sha256:83fd05fe114ed15c3975333c90cbe18c782d9c4d5c7ad6fdb8cc835e380ba505
    Port:          <none>
    Host Port:     <none>
    Args:
      node-controller
      -v=3
      --kube-node-name=$(KUBE_NODE_NAME)
    State:      Terminated
      Reason:   Error
      Message:  E1010 09:06:13.277883   66349 main.go:148] "unable to execute command" err="DirectPVNode.directpv.min.io \"kind-worker\" is invalid: status.devices: Required value"

      Exit Code:  1
      Started:    Thu, 10 Oct 2024 10:06:13 +0100
      Finished:   Thu, 10 Oct 2024 10:06:13 +0100
    Last State:   Terminated
      Reason:     Error
      Message:    E1010 09:05:56.773748   66257 main.go:148] "unable to execute command" err="DirectPVNode.directpv.min.io \"kind-worker\" is invalid: status.devices: Required value"

      Exit Code:    1
      Started:      Thu, 10 Oct 2024 10:05:56 +0100
      Finished:     Thu, 10 Oct 2024 10:05:56 +0100
    Ready:          False
    Restart Count:  2
```
Note1: kind-worker is my worker node name.

Note2: I configured kind so that the the docker volume mounted into the node for kubernetes local persistent storage is on an XFS drive.

If applicable, add screenshots to help explain your problem. Or logs from the pods in directpv-min-io namespace.

**Deployment information (please complete the following information):**
 - DirectPV version: v4.1.4
 - Kubernetes Version: 1.31
 - OS info: Ubuntu 22.04.5 (But kind node images are Debian 12)
- Kernel version: 6.8.0-45 Ubuntu

**Additional Note**
The doc says the daemonset needs Port 30443 for readiness handlers
It doesn't say in which dimension.
Should I create a Loadbalancer SVC ?
Not sure it is related to the error though.
